name: Publish release
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action@master
      env:
        CI_BUILD: true
      with:
        args:
          build
    - name: Docker Retag
      run: |
        docker image tag bookstorecw1/shipping-service:latest bookstorecw1/shipping-service:${GITHUB_REF#refs/*/}
    - name: Docker push
      run: |
        docker push bookstorecw1/shipping-service:${GITHUB_REF#refs/*/}
